version: "3"
services:
  app:
   build:
    context: .
    dockerfile: Dockerfile_app
   env_file:
    - .env_app
   ports:
    - "8080:8080"
   volumes:
    - "./src:/root/chrome_chat_server"
   depends_on:
    - postgres

  postgres:
    image: postgres:10.7
    container_name: "postgres"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - .env_postgres
    environment:
        TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    user: root
